let snapshot=null,installJobs=[],designJobs=[];
const originalRender=render;
modules.splice(2,0,['WIP','▥','Track production work in progress']);
const banner=document.querySelector('.preview');
banner.innerHTML='READ-ONLY PREVIEW · Live portal remains unchanged. <button class="button" id="importBackup">Import portal backup</button><input hidden type="file" id="backupFile" accept=".json,application/json"><span id="dataStatus" style="margin-left:12px">Loading local snapshot…</span>';
document.getElementById('importBackup').onclick=()=>document.getElementById('backupFile').click();
document.getElementById('backupFile').onchange=async e=>{try{const payload=JSON.parse(await e.target.files[0].text());const source=payload.data?.boardStore||payload.boardStore||payload;if(!Array.isArray(source.jobs)||!Array.isArray(source.designBoard?.cards))throw Error('Choose a portal backup containing jobs and designBoard.cards.');loadSnapshot({board:source,installers:payload.data?.installers||payload.installers||snapshot?.installers||[],label:'Imported backup '+(payload.exportedAt||'')});toast('Backup loaded into browser memory only');}catch(err){toast(err.message)}e.target.value=''};
function mapJob(j,design=false){return {ref:esc(j.orderReference||'Unreferenced'),client:esc(j.customerName||'Unnamed customer'),name:esc(j.description||'No description'),date:esc(j.date||j.scheduledDate||'Unscheduled'),person:esc(Array.isArray(j.installers)?j.installers.join(', '):j.assignedDesigner||j.designer||j.installers||'Unassigned'),status:esc(j.status|| (design?'Status not captured':j.date?'Scheduled':'Unscheduled')),value:esc(j.displayValue||(j.netTotal==null?'—':'£'+Number(j.netTotal).toLocaleString('en-GB'))),type:esc(j.category||j.jobType||''),notes:esc(j.notes||j.designerNote||'')}}
function loadSnapshot(data){snapshot=data;installJobs=(data.board.jobs||[]).map(j=>mapJob(j));designJobs=(data.board.designBoard?.cards||[]).map(j=>mapJob(j,true));jobs=installJobs;document.getElementById('dataStatus').textContent=data.label+' · '+installJobs.length+' installs · '+designJobs.length+' design jobs';render()}
render=function(){if(!snapshot){originalRender();return}jobs=current==='Design Board'?designJobs:installJobs;originalRender();
if(current==='WIP'){const records=snapshot.board.wipBoard?.cards;el.innerHTML=head('Track production work in progress.')+(records?.length?'<section class="panel"><div class="panel-head"><h2>Production jobs</h2><span class="muted">Read-only snapshot</span></div>'+records.map(r=>'<div class="activity"><b>'+esc(r.orderNumber||r.orderReference||'Unreferenced')+' · '+esc(r.company||r.customerName||'')+'</b><p>'+esc(r.description||'')+'</p><span class="muted">'+esc(r.status||r.stage||'')+'</span></div>').join('')+'</section>':'<section class="panel empty">WIP is included in the rebuild. Its production records were not part of the captured installation and design board views. Import a full portal backup to display WIP records here.</section>');return}
if(current==='Dashboard'){el.innerHTML=head('Your portal data, in a separate read-only workspace.')+'<div class="stats">'+[['Installation jobs',installJobs.length],['Design jobs',designJobs.length],['Subcontractors',snapshot.installers.length],['Holiday requests',snapshot.board.holidayRequests?.length??'Not loaded']].map(([a,b])=>'<div class="panel stat">'+a+'<strong>'+b+'</strong><span class="muted">From snapshot</span></div>').join('')+'</div><section class="panel"><div class="panel-head"><h2>Installation jobs</h2><button class="button" onclick="navigate(\'Installation Board\')">View board →</button></div>'+rows()+(jobs.length?'':'<div class="empty">No installation jobs in this local snapshot. Import a live portal backup to view current jobs.</div>')+'</section><div class="module-grid">'+modules.slice(1).map(([n,i,d])=>'<button class="panel module" onclick="navigate(\''+n+'\')"><span class="symbol">'+i+'</span><h2>'+n+'</h2><p>'+d+'</p></button>').join('')+'</div>'}
if(current==='Installation Board'||current==='Design Board'){const filtered=jobs.filter(j=>(j.ref+' '+j.client+' '+j.name).toLowerCase().includes(query.toLowerCase()));const keys=[...new Set(filtered.map(j=>current==='Design Board'?j.status:j.date))].sort();const container=el.querySelector('.board');if(container){container.style.gridTemplateColumns='repeat(auto-fit,minmax(240px,1fr))';container.innerHTML=keys.map(key=>'<section class="column"><h2>'+key+' <span class="muted">'+filtered.filter(j=>(current==='Design Board'?j.status:j.date)===key).length+'</span></h2>'+filtered.filter(j=>(current==='Design Board'?j.status:j.date)===key).map(card).join('')+'</section>').join('')||'<div class="panel empty">No jobs in this snapshot. Import a live backup to populate this board.</div>'}el.querySelectorAll('button').forEach(b=>{if(b.textContent.includes('Add job'))b.remove()})}
if(current==='Subcontractors'){el.innerHTML=head('Your subcontractor directory · Read-only snapshot')+'<section class="panel"><div class="panel-head"><h2>Installation partners</h2><span class="muted">'+snapshot.installers.length+' partners</span></div>'+snapshot.installers.map(s=>'<div class="activity"><b>'+esc(s.company||s.name)+'</b><span>'+esc(s.name)+'</span><p style="margin:5px 0">'+esc(s.address||'')+'</p><span class="muted">'+esc((s.regions||[]).join(', '))+'</span></div>').join('')+'</section>'}
if(current==='Holidays'||current==='Attendance'||current==='Notifications'){const records=current==='Holidays'?(snapshot.board.holidayRequests||[]):current==='Attendance'?(snapshot.board.attendanceEntries||[]):(snapshot.board.notifications||[]);el.innerHTML=head('Read-only records from your portal snapshot.')+'<section class="panel">'+(records.length?records.map(r=>'<div class="activity"><b>'+esc(r.employeeName||r.userName||r.name||r.title||'Record')+'</b><span>'+esc(r.message||r.status||r.date||r.startDate||'')+'</span></div>').join(''):'<div class="empty">No records in this snapshot.</div>')+'</section>'}
if(current==='Pro-Forma'){el.innerHTML=head('The existing PDF output is preserved.')+'<section class="panel" style="padding:26px"><h2>Your approved PDF design stays unchanged</h2><p>The original template, print layout, calculations and PDF generation code have not been edited. This draft does not generate replacement pro-formas.</p><p class="notice">Continue generating PDFs in the existing portal. The rebuild will use the established generator when functionality is connected.</p></section>'}
el.querySelectorAll('form').forEach(f=>{f.onsubmit=e=>{e.preventDefault();toast('Read-only preview — nothing saved')}})};
const originalDetail=detail;detail=function(i){originalDetail(i);const d=document.getElementById('modal');d.querySelectorAll('button.primary').forEach(b=>b.remove());d.querySelectorAll('textarea').forEach(t=>{t.value=jobs[i].notes.replace(/&amp;/g,'&');t.readOnly=true});if(current==='Design Board'){d.querySelectorAll('.muted').forEach(x=>{if(x.textContent==='Scheduled')x.textContent='Date added'})}const note=d.querySelector('p.muted');if(note)note.textContent='Portal snapshot · Read-only · No live changes'};
fetch('/snapshot').then(r=>{if(!r.ok)throw Error('Snapshot unavailable');return r.json()}).then(loadSnapshot).catch(()=>{document.getElementById('dataStatus').textContent='Import a portal backup to load your data'});

